<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="localhost.localdomain" ignored="0" name="report" tests="3" failures="1" timestamp="13 May 2019 21:18:37 GMT" time="0.073" errors="0">
  <testcase name="test1" time="0.003" classname="com.whh.extentreport.ExtentReport1">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at com.whh.extentreport.ExtentReport1.test1(ExtentReport1.java:10)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.0" classname="com.whh.extentreport.ExtentReport1"/>
  <testcase name="test3" time="0.0" classname="com.whh.extentreport.ExtentReport1"/>
</testsuite> <!-- report -->
